server:
  port: 8772
  mvc:
    servlet:
      load-on-startup: 100


# 实体类别名
mybatis:
  type-aliases-package: com.buba.stuinfomanager.pojo
  #扫描mapper
  mapper-locations: classpath:com.buba.stuinfomanager.mapper/*.xml

# 数据源配置
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/stuinfomanager?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource